#!/usr/bin/env python3
"""
build_poster_milestone1.py
--------------------------
Build poster-ready milestone artifacts from real GWAS intake outputs.

This script uses already produced QC files from run_gwas_intake_validation.py:
- data/processed/qc/gwas_harmonization_qc.tsv
- data/processed/qc/gwas_gtex_overlap_Whole_Blood.tsv

Outputs:
- results/tables/poster_gwas_intake_qc.tsv
- results/tables/poster_gtex_overlap_qc.tsv
- results/figures/poster_gwas_intake_funnel.png
- results/figures/poster_gtex_overlap_fraction.png
- docs/poster/results_milestone1.md
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Build poster milestone outputs from intake QC artifacts")
    p.add_argument("--base-dir", default=".", help="Repository root")
    p.add_argument(
        "--overlap-tissue",
        default="Whole_Blood",
        help="Tissue name used in overlap QC filename",
    )
    return p.parse_args()


def _ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def _read_required(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required input not found: {path}")
    return pd.read_csv(path, sep="\t")


def _plot_intake_funnel(qc_row: pd.Series, out_path: Path) -> None:
    labels = ["Input", "Lifted", "Final retained"]
    values = [
        int(qc_row["input_snp_count"]),
        int(qc_row["lifted_snp_count"]),
        int(qc_row["final_retained_snp_count"]),
    ]

    fig, ax = plt.subplots(figsize=(8, 4.5))
    bars = ax.bar(labels, values)
    ax.set_title("GWAS intake and harmonization counts")
    ax.set_ylabel("SNP count")
    ax.grid(axis="y", alpha=0.25)

    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{val:,}", ha="center", va="bottom")

    fig.tight_layout()
    fig.savefig(out_path, dpi=300)
    plt.close(fig)


def _plot_overlap_fraction(overlap_row: pd.Series, out_path: Path) -> None:
    gwas_n = int(overlap_row["gwas_unique_varids"])
    overlap_n = int(overlap_row["overlap_varids"])
    non_overlap_n = max(gwas_n - overlap_n, 0)

    labels = ["Overlap", "Not overlap"]
    values = [overlap_n, non_overlap_n]

    fig, ax = plt.subplots(figsize=(8, 4.5))
    bars = ax.bar(labels, values)
    ax.set_title(f"GTEx model overlap ({overlap_row['tissue']})")
    ax.set_ylabel("GWAS varID count")
    ax.grid(axis="y", alpha=0.25)

    for bar, val in zip(bars, values):
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), f"{val:,}", ha="center", va="bottom")

    fig.tight_layout()
    fig.savefig(out_path, dpi=300)
    plt.close(fig)


def _write_markdown_summary(qc_row: pd.Series, overlap_row: pd.Series, out_path: Path) -> None:
    text = "# Poster Results: Milestone 1 (Real Data Intake)\n\n"
    text += "This file is generated by `scripts/build_poster_milestone1.py`.\n\n"
    text += "## GWAS Harmonization QC\n\n"
    text += f"- Input SNPs: **{int(qc_row['input_snp_count']):,}**\n"
    text += f"- Lifted SNPs: **{int(qc_row['lifted_snp_count']):,}**\n"
    text += f"- Failed liftover: **{int(qc_row['failed_liftover_count']):,}**\n"
    text += f"- Palindromic dropped: **{int(qc_row['palindromic_dropped_count']):,}**\n"
    text += f"- Final retained SNPs: **{int(qc_row['final_retained_snp_count']):,}**\n\n"
    text += "## GTEx Model Namespace Overlap\n\n"
    text += f"- Tissue: **{overlap_row['tissue']}**\n"
    text += f"- GWAS unique varIDs: **{int(overlap_row['gwas_unique_varids']):,}**\n"
    text += f"- Model unique varIDs: **{int(overlap_row['model_unique_varids']):,}**\n"
    text += f"- Overlap varIDs: **{int(overlap_row['overlap_varids']):,}**\n"
    text += f"- Overlap fraction: **{float(overlap_row['overlap_fraction']):.6f}**\n\n"
    text += "## Figures\n\n"
    text += "- `results/figures/poster_gwas_intake_funnel.png`\n"
    text += "- `results/figures/poster_gtex_overlap_fraction.png`\n"

    out_path.write_text(text, encoding="utf-8")


def main() -> int:
    args = parse_args()
    base_dir = Path(args.base_dir).resolve()

    qc_dir = base_dir / "data" / "processed" / "qc"
    harm_qc_path = qc_dir / "gwas_harmonization_qc.tsv"
    overlap_qc_path = qc_dir / f"gwas_gtex_overlap_{args.overlap_tissue}.tsv"

    harm_qc = _read_required(harm_qc_path)
    overlap_qc = _read_required(overlap_qc_path)

    if harm_qc.empty:
        raise RuntimeError(f"No rows in {harm_qc_path}")
    if overlap_qc.empty:
        raise RuntimeError(f"No rows in {overlap_qc_path}")

    qc_row = harm_qc.iloc[0]
    overlap_row = overlap_qc.iloc[0]

    table_dir = base_dir / "results" / "tables"
    fig_dir = base_dir / "results" / "figures"
    poster_doc_dir = base_dir / "docs" / "poster"
    _ensure_dir(table_dir)
    _ensure_dir(fig_dir)
    _ensure_dir(poster_doc_dir)

    harm_out = table_dir / "poster_gwas_intake_qc.tsv"
    overlap_out = table_dir / "poster_gtex_overlap_qc.tsv"
    harm_qc.to_csv(harm_out, sep="\t", index=False)
    overlap_qc.to_csv(overlap_out, sep="\t", index=False)

    _plot_intake_funnel(qc_row, fig_dir / "poster_gwas_intake_funnel.png")
    _plot_overlap_fraction(overlap_row, fig_dir / "poster_gtex_overlap_fraction.png")

    _write_markdown_summary(
        qc_row,
        overlap_row,
        poster_doc_dir / "results_milestone1.md",
    )

    print("Built poster milestone outputs:")
    print(f"- {harm_out}")
    print(f"- {overlap_out}")
    print(f"- {fig_dir / 'poster_gwas_intake_funnel.png'}")
    print(f"- {fig_dir / 'poster_gtex_overlap_fraction.png'}")
    print(f"- {poster_doc_dir / 'results_milestone1.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
